#  __       __  _______    ______    ______  
#  /  \     /  |/       \  /      \  /      \ 
#  $$  \   /$$ |$$$$$$$  |/$$$$$$  |/$$$$$$  |
#  $$$  \ /$$$ |$$ |  $$ |$$ |  $$/ $$ |__$$ |
#  $$$$  /$$$$ |$$ |  $$ |$$ |      $$    $$ |
#  $$ $$ $$/$$ |$$ |  $$ |$$ |   __ $$$$$$$$ |
#  $$ |$$$/ $$ |$$ |__$$ |$$ \__/  |$$ |  $$ |
#  $$ | $/  $$ |$$    $$/ $$    $$/ $$ |  $$ |
#  $$/      $$/ $$$$$$$/   $$$$$$/  $$/   $$/
#
#
# @author Adam Marshall <adam@appsynergy.net>
# @designer Julie Parys <julie.parys@arts-interactive.com>
# @copyright Adam Marshall, MDCA 2014

# Who are we?
name: Manx Digital Currency Association

# Markdown related stuff
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
pygments: true

# Where the things are
source:      ./src
destination: ./site

# Include and exclude some files
include: 
  - bootstrap/
  - .htaccess

# Plugins and other nice things
gems:
  - jekyll-sitemap

# Deployment with Glynn
ftp_host: '217.23.163.46'
ftp_dir: '/'
#ftp_passive: false
#ftp_port: 21
# use STDIO
#ftp_username:
#ftp_password: